### ISSUE TITLE
showing the star rating of the map wolud be usefull 

### ISSUE THREAD

**Issue by Chromeilion** [omkelderman/osu-scores#28]
For a more comprehensive summery of the score, the star rating is something which should be shown, perhaps alongside the difficulty name.

**Comment by omkelderman** [comment]
fantastic idea, I love it!

And I do agree with the "alongside the difficulty name", seems the most logical to me. However that does create a problem for me: right now I dont know how wide a certain string is pixel-wise on the resulting picture, aka, if I want to place an amount of stars after the diff name I have no idea where to place it.

I see 3 posibilities:
1. Just put it in front of the diff name, its easy to calc how much pixels the amount of stars have taken up and just shift the diff name to the right
2. Put it behind the diff name, which would require calculating pixel width of an arbitrary string (totally doable, I have the font file so it is deterministic, just requires effort xD)
3. Put it somewhere else?

3 is kinda not doable, pretty much every space has been taken up by something (take into account that the song title, artist name and diff name all have a theoretical max width of infinity due to them being dependent of the string length)
I dont like 1, will look weird imo

So I guess I'll take a look in putting effort in making sure option 2 will work. I kinda need the "how many pixels is this string wide" calculations anyway if I ever want a proper fix for #4.

(and it also solves the problem where if the diff name would be super long for whatever reason I can scale it down a bit so the diff stars would still be visible somewhere on the resulting picture and not "fall off")

**Comment by omkelderman** [comment]
for my own reference: https://www.npmjs.com/package/opentype.js
